# Generated by Django 6.0.6 on 2026-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.CharField(default='cereqo/video/demo-lesson-video.mp4', max_length=255),
        ),
    ]
