# Generated by Django 6.0.6 on 2026-09-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_course_attendancesession_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='session_minutes',
            field=models.PositiveSmallIntegerField(default=75),
        ),
    ]
