# Generated by Django 6.0.6 on 2026-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.CharField(default='cereqo/img/mentors/cereqo-classroom.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Cereqo mentor', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_role',
            field=models.CharField(default='SAT mentor', max_length=100),
        ),
    ]
